# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build the app and push Docker Image to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn clean compile -DskipTests=true
    - name: Build with Maven
      run: mvn clean package -DskipTests=true
      # https://github.com/marketplace/actions/docker-build-push-action
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: khadijaelm24/githubactions
        tags: latest # keeping simply a single tag for a docker image's push
        registry: docker.io # same registry's name 
        dockerfile: Dockerfile # references to the written Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  Test-on-cluster:

    runs-on: ubuntu-latest

    needs: [build]
    
    steps:
      - name: Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - run: |
          kubectl cluster-info
          kubectl get nodes
      - name : Preparing cluster for githubactions
        run: |
          kubectl apply -f https://raw.githubusercontent.com/khadijaelm24/Simple-springboot-GitHubActions-CICD/master/yamls/sa.yaml
          kubectl apply -f https://raw.githubusercontent.com/khadijaelm24/Simple-springboot-GitHubActions-CICD/master/yamls/crb.yaml
          kubectl run githubactions --image=ghcr.io/khadijaelm24/githubactions:c55a2505b40d03d0a82a77804e6a376e81243ab0 --port=8081
          sleep 20
          kubectl get po
          kubectl port-forward githubactions 8081:8081 &>/dev/null &
          sleep 5
          kubectl port-forward githubactions 8081:8081 &>/dev/null &
      # - run: |
      #     curl -i http://localhost:8081/     
